// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHwSbu9XVk3xI__jb7UrPs-jpARSdu500',
    appId: '1:620891604582:web:a024a49912c3fdad1a8fa7',
    messagingSenderId: '620891604582',
    projectId: 'attendance-flutter-9ccae',
    authDomain: 'attendance-flutter-9ccae.firebaseapp.com',
    databaseURL: 'https://attendance-flutter-9ccae-default-rtdb.firebaseio.com',
    storageBucket: 'attendance-flutter-9ccae.appspot.com',
    measurementId: 'G-RB6WKX24XX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB6I3kPYSUMu0pQspT34nASceLxPGnsbU',
    appId: '1:620891604582:android:18001cc2c35fdbd71a8fa7',
    messagingSenderId: '620891604582',
    projectId: 'attendance-flutter-9ccae',
    databaseURL: 'https://attendance-flutter-9ccae-default-rtdb.firebaseio.com',
    storageBucket: 'attendance-flutter-9ccae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdoxvJdqi7grOeDdcnmS6lH_2c2jsiQB0',
    appId: '1:620891604582:ios:d0e56702804ecbf61a8fa7',
    messagingSenderId: '620891604582',
    projectId: 'attendance-flutter-9ccae',
    databaseURL: 'https://attendance-flutter-9ccae-default-rtdb.firebaseio.com',
    storageBucket: 'attendance-flutter-9ccae.appspot.com',
    iosBundleId: 'com.academy.studysyncStudent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdoxvJdqi7grOeDdcnmS6lH_2c2jsiQB0',
    appId: '1:620891604582:ios:d0e56702804ecbf61a8fa7',
    messagingSenderId: '620891604582',
    projectId: 'attendance-flutter-9ccae',
    databaseURL: 'https://attendance-flutter-9ccae-default-rtdb.firebaseio.com',
    storageBucket: 'attendance-flutter-9ccae.appspot.com',
    iosBundleId: 'com.academy.studysyncStudent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHwSbu9XVk3xI__jb7UrPs-jpARSdu500',
    appId: '1:620891604582:web:c5b7b8dd6c3f9abc1a8fa7',
    messagingSenderId: '620891604582',
    projectId: 'attendance-flutter-9ccae',
    authDomain: 'attendance-flutter-9ccae.firebaseapp.com',
    databaseURL: 'https://attendance-flutter-9ccae-default-rtdb.firebaseio.com',
    storageBucket: 'attendance-flutter-9ccae.appspot.com',
    measurementId: 'G-6ERQXBQ1XL',
  );
}
